package org.example.enums;

public enum Permissions {
//    create, read, update, delete
    CREATE_DOCTOR, VIEW_DOCTOR, UPDATE_DOCTOR, DELETE_DOCTOR,
    CREATE_STAFF, VIEW_STAFF, UPDATE_STAFF, DELETE_STAFF,
    CREATE_PATIENT, VIEW_PATIENT, UPDATE_PATIENT, DELETE_PATIENT,
    CREATE_MEDICAL_RECORD, VIEW_MEDICAL_RECORD, UPDATE_MEDICAL_RECORD, DELETE_MEDICAL_RECORD,
    CREATE_APPOINTMENT, VIEW_APPOINTMENT, UPDATE_APPOINTMENT, DELETE_APPOINTMENT,
    CREATE_BILL, VIEW_BILL, UPDATE_BILL, DELETE_BILL,
    CREATE_PERMISSION, VIEW_PERMISSION, UPDATE_PERMISSION, DELETE_PERMISSION, NONE;
    
}
